<?php 
use Flow\Authenticate\Authenticate;
// include 'User.php';

// autoload_namespaces.php generated by Composer

// $vendorDir = dirname(dirname(__FILE__));
// $baseDir = dirname($vendorDir);


require_once (__DIR__) . '/vendor/autoload.php';
$test = new Authenticate;
$test->name = 'Fedya';
echo $test->name; 

